### ISSUE TITLE
Missing parentheses in call to 'print'. Did you mean print(...)?

### ISSUE THREAD

**Issue by sergenti** [samba/markdown2pdf#1]
` python -m markdown2pdf -i input.md -o output.pdf
` 
 Traceback (most recent call last):   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details     return _get_module_details(pkg_main_name, error)   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details     __import__(pkg_name)   File "/home/fyll/Documents/GitHub/random/env/lib/python3.10/site-packages/markdown2pdf/__init__.py", line 20     print css_file     ^^^^^^^^^^^^^^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by samba** [comment]
Hey thanks for raising this! 
I actually haven't worked on this project since 2014. 
At that time I was using strictly Python 2. 

I haven't actually used this Codebase in years, and I didn't know anyone else was using it, so I haven't actively maintained it. 


I'd welcome contributions if you want to help upgrade it to Python 3. Please feel free to open PRs with changes! :)

**Comment by samba** [comment]
In further review, I cannot find anywhere in this repository a `print` statement in actual Python code.  I find it once in the README. Also the error you cite refers to `init.py`, but no such file exists in this repository; additionally the error references `css_file` which is also not referenced in this repository.  

Could you verify the origin of this error, and the origin of the code you‘re actually trying to run? 

I wonder if there‘s another project somewhere with the same name, but not my code.

If it‘s coming from someone else‘s code, please consider closing this issue.
